# Generated by Django 5.1 on 2024-11-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0004_pageview_post_comment_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='5RS CONSTRUCTION SERVICES', max_length=200)),
                ('subtitle', models.TextField()),
                ('button_text', models.CharField(default='Call us Now!', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text="CSS class for the icon, e.g., 'bx bxs-coffee-bean'", max_length=50)),
                ('link', models.URLField(blank=True, help_text='Optional URL for more info', null=True)),
            ],
        ),
    ]
