# Generated by Django 5.1 on 2024-11-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0007_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='read_status',
            new_name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
