# Generated by Django 5.1 on 2024-11-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0008_rename_read_status_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
