# Generated by Django 5.1 on 2024-11-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0009_contact_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('contact_submission', 'New Contact Form Submission')], default='contact_submission', max_length=50),
        ),
    ]
