# Generated by Django 5.1 on 2024-11-09 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0010_notification_details_notification_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_read',
        ),
    ]
