# Generated by Django 5.1 on 2024-11-09 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0014_contactsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSubmission',
        ),
    ]
