# Generated by Django 5.1 on 2024-11-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0018_adminmessage_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
