# Generated by Django 5.1 on 2024-11-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0020_pendingwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingwork',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingwork',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
