# Generated by Django 5.1 on 2024-11-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0021_pendingwork_deleted_at_pendingwork_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.jpg', upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.jpg', upload_to='profile_pictures/'),
        ),
    ]
