# Generated by Django 5.1 on 2024-11-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0022_profile_profile_picture_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
