# Generated by Django 5.1 on 2024-12-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0025_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
