# Generated by Django 5.1 on 2025-01-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0028_energyconsumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteconfiguration',
            name='about_us_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/'),
        ),
        migrations.AddField(
            model_name='websiteconfiguration',
            name='about_us_text_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteconfiguration',
            name='about_us_text_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteconfiguration',
            name='about_us_text_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websiteconfiguration',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='websiteconfiguration',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='websiteconfiguration',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='websiteconfiguration',
            name='facebook_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websiteconfiguration',
            name='footer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websiteconfiguration',
            name='site_name',
            field=models.CharField(max_length=100),
        ),
    ]
