# Generated by Django 5.1 on 2025-01-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0030_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
