# Generated by Django 5.1 on 2025-01-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0031_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteconfiguration',
            name='project_description_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteconfiguration',
            name='project_description_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteconfiguration',
            name='project_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='websiteconfiguration',
            name='project_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='websiteconfiguration',
            name='project_title_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='websiteconfiguration',
            name='project_title_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
