# Generated by Django 5.1 on 2025-01-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0033_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteconfiguration',
            name='project_description_1',
        ),
        migrations.RemoveField(
            model_name='websiteconfiguration',
            name='project_description_2',
        ),
        migrations.RemoveField(
            model_name='websiteconfiguration',
            name='project_image_1',
        ),
        migrations.RemoveField(
            model_name='websiteconfiguration',
            name='project_image_2',
        ),
        migrations.RemoveField(
            model_name='websiteconfiguration',
            name='project_title_1',
        ),
        migrations.RemoveField(
            model_name='websiteconfiguration',
            name='project_title_2',
        ),
        migrations.AddField(
            model_name='websiteconfiguration',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='website_configurations', to='edward.project'),
        ),
    ]
