# Generated by Django 5.1 on 2025-01-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0034_remove_websiteconfiguration_project_description_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteconfiguration',
            name='projects',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
