# Generated by Django 5.1 on 2025-01-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0036_project_websiteconfiguration_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteconfiguration',
            name='projects',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
