# Generated by Django 5.1 on 2025-01-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0037_remove_websiteconfiguration_projects_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteconfiguration',
            name='portfolio_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='websiteconfiguration',
            name='portfolio_text_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='websiteconfiguration',
            name='portfolio_text_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
