# Generated by Django 5.1 on 2025-04-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0046_alter_notification_options_remove_notification_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingwork',
            old_name='deleted_at',
            new_name='completed_at',
        ),
        migrations.AlterField(
            model_name='pendingwork',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
