# Generated by Django 5.1 on 2025-04-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0047_rename_deleted_at_pendingwork_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
