# Generated by Django 5.1 on 2025-04-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0050_realtimeenergydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtimeenergydata',
            old_name='power_kw',
            new_name='energy_1',
        ),
        migrations.AddField(
            model_name='realtimeenergydata',
            name='energy_2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='realtimeenergydata',
            name='total_energy',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realtimeenergydata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
