# Generated by Django 5.1 on 2025-04-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0054_powerreading_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_battery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_forecast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_leaderboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_weather',
            field=models.BooleanField(default=True),
        ),
    ]
