# Generated by Django 5.1 on 2025-04-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0055_profile_show_battery_profile_show_forecast_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='show_battery',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_forecast',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_leaderboard',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_weather',
        ),
    ]
