# Generated by Django 5.1 on 2025-04-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0056_remove_profile_show_battery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
