# Generated by Django 5.1 on 2025-05-07 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0057_pageview_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='powerreading',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='powerreading',
            name='battery_percentage',
            field=models.FloatField(default=0.0, help_text='Battery charge (%)'),
        ),
        migrations.AddField(
            model_name='powerreading',
            name='battery_voltage',
            field=models.FloatField(default=0.0, help_text='Battery voltage (V)'),
        ),
        migrations.AddField(
            model_name='powerreading',
            name='current1',
            field=models.FloatField(default=0.0, help_text='Current Line 1 (A)'),
        ),
        migrations.AddField(
            model_name='powerreading',
            name='current2',
            field=models.FloatField(default=0.0, help_text='Current Line 2 (A)'),
        ),
        migrations.AddField(
            model_name='powerreading',
            name='energy1',
            field=models.FloatField(default=0.0, help_text='Energy consumed on line 1 (kWh)'),
        ),
        migrations.AddField(
            model_name='powerreading',
            name='energy2',
            field=models.FloatField(default=0.0, help_text='Energy consumed on line 2 (kWh)'),
        ),
        migrations.AddField(
            model_name='powerreading',
            name='frequency1',
            field=models.FloatField(default=0.0, help_text='Frequency line 1 (Hz)'),
        ),
        migrations.AddField(
            model_name='powerreading',
            name='frequency2',
            field=models.FloatField(default=0.0, help_text='Frequency line 2 (Hz)'),
        ),
        migrations.AddField(
            model_name='powerreading',
            name='power_factor1',
            field=models.FloatField(default=0.0, help_text='Power Factor line 1'),
        ),
        migrations.AddField(
            model_name='powerreading',
            name='power_factor2',
            field=models.FloatField(default=0.0, help_text='Power Factor line 2'),
        ),
        migrations.AddField(
            model_name='powerreading',
            name='voltage1',
            field=models.FloatField(default=0.0, help_text='Voltage Line 1 (V)'),
        ),
        migrations.AddField(
            model_name='powerreading',
            name='voltage2',
            field=models.FloatField(default=0.0, help_text='Voltage Line 2 (V)'),
        ),
        migrations.AlterField(
            model_name='powerreading',
            name='power1',
            field=models.FloatField(default=0.0, help_text='Power from source 1 (Watts)'),
        ),
        migrations.AlterField(
            model_name='powerreading',
            name='power2',
            field=models.FloatField(default=0.0, help_text='Power from source 2 (Watts)'),
        ),
        migrations.AlterField(
            model_name='powerreading',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_readings', to=settings.AUTH_USER_MODEL),
        ),
    ]
