# Generated by Django 5.1 on 2025-05-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edward', '0058_alter_powerreading_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PowerLog',
        ),
    ]
