from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import home, login_selection,user_login,admin_login,create_client_account,user_dashboard,custom_logout, admin_dashboard,admin_logout,user_management, site_statistics, edit_user, delete_user, website_configuration, update_account, delete_contact,archived_contacts, energy_monitoring,delete_all_archived_contacts, reply_to_contact, mark_work_complete, add_pending_work,pending_work_list, delete_work, delete_completed_work,restore_completed_work, add_user, change_profile, contact_submissions_page, mark_notification_read, notifications_view,send_notification,delete_notification,change_password,export_users_csv,create_admin_account,check_new_notifications,record_energy_data, historical_power_data, monthly_power_data,receive_energy_data,grouped_power_data,user_faq,save_power_reading,live_energy_totals,ingest_power_reading,last_data_timestamp,report_data,report_csv,report_pdf,save_live_reading,filtered_dashboard_data,power_summary_timestamps


urlpatterns = [
    path('', home, name='home'),
    path('choose-login/', login_selection, name='login_selection'),
    path('login/', user_login, name='user_login'),
    path('admin-login/', admin_login, name='admin_login'),
    path('user-dashboard/', user_dashboard, name='user_dashboard'),
    path('logout/', custom_logout, name='logout'), # Logout view
    path('admin-dashboard/', admin_dashboard, name='admin_dashboard'),
    path('admin-logout/', admin_logout, name='admin_logout'),
    path('custom-admin/user-management/', user_management, name='user_management'),
    path('custom-admin/site-statistics/', site_statistics, name='site_statistics'),
    path('custom-admin/user-management/edit/<int:user_id>/', edit_user, name='edit_user'),
    path('custom-admin/user-management/delete/<int:user_id>/', delete_user, name='delete_user'),
    path('custom-admin/website-configuration/', website_configuration, name='website_configuration'),
    path('update-account/', update_account, name='update_account'),
    path('delete_contact/<int:contact_id>/', delete_contact, name='delete_contact'),
    path('archived_contacts/', archived_contacts, name='archived_contacts'),
    path('energy-monitoring/', energy_monitoring, name='energy_monitoring'),
    path('custom-admin/delete-all-archived-contacts/', delete_all_archived_contacts, name='delete_all_archived_contacts'),
    path('reply-contact/<int:contact_id>/', reply_to_contact, name='reply_to_contact'),
    path('mark-work-complete/<int:work_id>/', mark_work_complete, name='mark_work_complete'),
    path('pending-work/', pending_work_list, name='pending_work_list'),
    path('pending-work/add/', add_pending_work, name='add_pending_work'),
    path('delete-work/<int:work_id>/', delete_work, name='delete_work'),
    path('delete-completed/<int:work_id>/', delete_completed_work, name='delete_completed_work'),
    path('restore-completed/<int:work_id>/', restore_completed_work, name='restore_completed_work'),
    path('add_user/', add_user, name='add_user'),
    path('change-profile/', change_profile, name='change_profile'),
    path('contacts/', contact_submissions_page, name='contact_submissions_page'),
    path('notifications/<int:pk>/read/', mark_notification_read, name='mark_notification_read'),
    path('notifications/', notifications_view, name='notifications'), 
    path('send-notification/', send_notification, name='send_notification'),
    path('mark_notification_read/<int:notif_id>/', mark_notification_read, name='mark_notification_read'),
    path("delete_notification/<int:notification_id>/", delete_notification, name="delete_notification"),
    path('change-password/', change_password, name='change_password'),
    path('export-users-csv/', export_users_csv, name='export_users_csv'),
    path('signup/', create_client_account, name='create_client_account'),
    path('admin/add-user/', create_admin_account, name='admin_add_user'),
    path("check_new_notifications/", check_new_notifications, name="check_new_notifications"),
    path('record-energy/', record_energy_data, name='record_energy'),
    path('historical-power-data/', historical_power_data, name='historical_power'),
    path('api/historical-power-data/', historical_power_data, name='historical_power'),
    path("api/historical-power/", historical_power_data, name="historical_power_data"),
    path('monthly-power-data/', monthly_power_data, name='monthly_power_data'),
    path('api/energy-data/', receive_energy_data, name='receive_energy_data'),
    path('grouped-power-data/', grouped_power_data, name='grouped_power_data'),
    path('api/ingest-power/', ingest_power_reading, name='ingest-power'),
    path('api/grouped-power-data/', grouped_power_data, name='grouped-power-data'),
    path('faq/', user_faq, name='user_faq'),
    path('api/save-reading/', save_power_reading, name='save_reading'),
    path("api/live-energy-totals/", live_energy_totals, name="live_energy_totals"),
    path("api/last-data-time/", last_data_timestamp, name="last_data_timestamp"),
    path("api/report/", report_data, name="report_data"),
    path("api/report/export/", report_csv, name="report_csv"),
    path("api/report/pdf/", report_pdf, name="report_pdf"),
    path("api/save-live-reading/", save_live_reading, name="save_live_reading"),
    path("api/filtered-dashboard/", filtered_dashboard_data, name="filtered_dashboard"),
    path("api/summary-timestamps/", power_summary_timestamps, name="power_summary_timestamps"),

    ]